name: Powershell Documentation Creation

on:
  push:
    branches: ["Get-RGCreationDate"]
  pull_request:
    branches: ["main"]

jobs:
  DocCreate:
    name: DocCreate
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Documentation
        run: ./.github/workflows/PSDocumentation.ps1

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /
