name: Powershell Documentation Creation

on:
  pull_request:
    branches: ["main"]

jobs:
  DocCreate:
    name: DocCreate
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Create Documentation
        run: .\.github\workflows\PSDocumentationCreate.ps1

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
