name: Powershell Security Scan

on:
  pull_request:
    branches: ["main"]

jobs:
  PSScan:
    name: PSScan
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Folder
        run: mkdir scans

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          output-filename: devskim-results.sarif
          output-directory: scans

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\
          recurse: true
          output: scans/PSScriptAnalyzer-results.sarif

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scans/
